### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = false # automatically start the local network container, if not already running
network = "testing"
[[development.accounts]]
name = "me" # Required. Keys for this account will be saved to `./.stellar/identity`
default = true # Optional. Whether to use this account as the `--source` for commands that need one.

[development.contracts]
# Generate a contract client (NPM package) for this contract. This means:
#   - compile (build) the contract source to Wasm
#   - deploy the contract to the `network` specified above
#   - run any `init` script specified below
#   - generate an NPM client (also called the "TS Bindings") for the deployed
#     contract to the NPM workspace in `packages/*`
#   - import the contract for easy access in the frontend in `src/contracts`
#
# You can only use `client = true` when:
#   - the contract source must be part of the local Cargo workspace (in the
#     PROJECT_ROOT/contracts folder)
#   - The specified name here ("soroban_hello_world_contract") must match the
#     underscored-version of the `name` in the contract's Cargo.toml.
#   - The environment is `development` or `test`
# Rather than in one list, TOML allows specifying contracts in their own "sections"
[development.contracts.iss]
client = true

# If your contract has a `__constructor`, specify your arguments to it here.
# These are the same arguments you could pass after the `--` in a call to
# `stellar contract deploy`
# Only available in `development` and `test` environments
# TODO add appropriate values for for the constructors arguments
# constructor_args = """
# --owner "GDNS3FTRI64VM7YX2INGTZ4VRAEZ62EUYLJ43OXQLOFTSUXSIJ7C2HJL"
# """

[development.contracts.spaceman]
client = true

[testing.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[testing.accounts]]
name = "testnet-user"
default = true

[testing.contracts]
[testing.contracts.iss]
id = "CC4XOC2WQ6GQK7RQ3Q3DYIORMUTRP6CU7VWKVJWRE3HBUJY27GSFDWHR"

[testing.contracts.spaceman]
id = "CCORFIQVPI55SWQJXUHZCLXB5Q4FGU3LN222XGWMMUPKA7TPXJKBY6RV"

# soroban-atomic-swap-contract = "C123..."
# soroban-auth-contract = "C234..."
# soroban-errors-contract = "C345..."
# soroban-hello-world-contract = "C456..." 
# soroban-increment-contract = "C567..."
# soroban-token-contract = "C678..."
# eurc = "C789..."


### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
# soroban-atomic-swap-contract = "C987..."
# soroban-auth-contract = "C876..."
# soroban-errors-contract = "C765..."
# soroban-hello-world-contract = "C654..."
# soroban-increment-contract = "C543..."
# soroban-token-contract = "C432..."
# eurc = "C321..."
